### ISSUE TITLE
Egg just dosen't work

### ISSUE THREAD

**Issue by ghost** [YoungHamster/EvilEgg_minecaft_plugin#1]
As the description says to place crimson nylium then crimson roots on top i have tried that and nothing happened when i place the crimson nylium it just says nothing bad happened after placing the roots it does completey nothing

**Comment by TheAwesome98-Real** [comment]
can we have information about your computer, server, server logs, etc

**Comment by YoungHamster** [comment]
The latest version that i wrote about 6 months ago doesn't work on my pc either

**Comment by YoungHamster** [comment]
Uploaded new release, it works
